# Related contents configuration
includeNewer = true
threshold = 60
toLower = false

[[indices]]
name = "skills"
weight = 100

[[indices]]
name = "tags"
weight = 200

[[indices]]
name = "categories"
weight = 300
